# Numpy

NumPy is the core library for scientific computing in Python. It provices a highh-performance multidimensional array object, and tools for working with arrays.


## Importing Numpy
***

In [103]:
# How to import numpy
import numpy as np
# How to check the version of the numpy package
print('numpy', np.__version__)
# Checking the avaiable methods
print(dir(np))


numpy 1.23.3
['ALLOW_THREADS', 'AxisError', 'BUFSIZE', 'CLIP', 'ComplexWarning', 'DataSource', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'ModuleDeprecationWarning', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'Tester', 'TooHardError', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'VisibleDeprecationWarning', 'WRAP', '_CopyMode', '_NoValue', '_UFUNC_API', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__deprecated_attrs__', '__dir__', '__doc__', '__expired_functions__', '__file__', '__getattr__', '__git_version__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_add_newdoc_ufunc', '_d

## Creating numpy array using
***

### Creating int numpy arrays


In [104]:
# Creating python List
python_list = [1, 2, 3, 4, 5]

# Checking data types
print('Type:', type(python_list))  # <class 'list'>
print(python_list)  # [1, 2, 3, 4, 5]

two_dimensional_list = [[0, 1, 2], [3, 4, 5], [6, 7, 8]]

print(two_dimensional_list)  # [[0, 1, 2], [3, 4, 5], [6, 7, 8]]

# Creating Numpy(Numerical Python) array from python list

numpy_array_from_list = np.array(python_list)
print(type(numpy_array_from_list))   # <class 'numpy.ndarray'>
print(numpy_array_from_list)  # array([1, 2, 3, 4, 5])


Type: <class 'list'>
[1, 2, 3, 4, 5]
[[0, 1, 2], [3, 4, 5], [6, 7, 8]]
<class 'numpy.ndarray'>
[1 2 3 4 5]


### Creating float numpy arrays

Creating a float numpy array from list with a float data type parameter


In [105]:
# Python list
python_list = [1, 2, 3, 4, 5]

numy_array_from_list2 = np.array(python_list, dtype=float)
print(numy_array_from_list2)  # array([1., 2., 3., 4., 5.])


[1. 2. 3. 4. 5.]


### Creating boolean numpy arrays

Creating a boolean a numpy array from list


In [106]:
numpy_bool_array = np.array([0, 1, -1, 0, 9], dtype=bool)
print(numpy_bool_array)  # array([False,  True,  True, False, False])


[False  True  True False  True]


### Creating multidimensional array using numpy

A numpy array may have one or multiple rows and columns


In [107]:
two_dimensional_list = [[0, 1, 2], [3, 4, 5], [6, 7, 8]]
numpy_two_dimensional_list = np.array(two_dimensional_list)
print(type(numpy_two_dimensional_list))
print(numpy_two_dimensional_list)


<class 'numpy.ndarray'>
[[0 1 2]
 [3 4 5]
 [6 7 8]]


### Creating numpy array to list


In [108]:
# We can always convert an array back to a python list using tolist().
np_to_list = numpy_array_from_list.tolist()
print(type(np_to_list))
print('one dimensional array:', np_to_list)
print('two dimensional array: ', numpy_two_dimensional_list.tolist())


<class 'list'>
one dimensional array: [1, 2, 3, 4, 5]
two dimensional array:  [[0, 1, 2], [3, 4, 5], [6, 7, 8]]


### Creating numpy array from tuple


In [109]:
# Numpy array from tuple
# Creating tuple in Python
python_tuple = (1, 2, 3, 4, 5)
print(type(python_tuple))  # <class 'tuple'>
print('python_tuple: ', python_tuple)  # python_tuple:  (1, 2, 3, 4, 5)

numpy_array_from_tuple = np.array(python_tuple)
print(type(numpy_array_from_tuple))  # <class 'numpy.ndarray'>
# numpy_array_from_tuple:  [1 2 3 4 5]
print('numpy_array_from_tuple: ', numpy_array_from_tuple)


<class 'tuple'>
python_tuple:  (1, 2, 3, 4, 5)
<class 'numpy.ndarray'>
numpy_array_from_tuple:  [1 2 3 4 5]


### Shape of numpy array

The shape method provide the shape of the array as a tuple. The first is the row and the second is the column. If the array is just one dimensional it returns the size of the array.


In [110]:
nums = np.array([1, 2, 3, 4, 5])
print(nums)
print(type(nums))
print('shape of nums: ', nums.shape)
print(numpy_two_dimensional_list)
print('shape of numpy_two_dimensional_list: ',
      numpy_two_dimensional_list.shape)
three_by_four_array = np.array([
    [0, 1, 2, 3],
    [4, 5, 6, 7],
    [8, 9, 10, 11]
])
print(three_by_four_array.shape)


[1 2 3 4 5]
<class 'numpy.ndarray'>
shape of nums:  (5,)
[[0 1 2]
 [3 4 5]
 [6 7 8]]
shape of numpy_two_dimensional_list:  (3, 3)
(3, 4)


### Data type of numpy array

Type of data types: str, int, float, complex, bool, list, None


In [111]:
int_lists = [-3, -2, -1, 0, 1, 2, 3]
int_array = np.array(int_lists)
float_array = np.array(int_lists, dtype=float)

print(int_array)
print(int_array.dtype)
print(float_array)
print(float_array.dtype)


[-3 -2 -1  0  1  2  3]
int32
[-3. -2. -1.  0.  1.  2.  3.]
float64


### Size of a numpy array

In numpy to know the number of items in a numpy array list we use size


In [112]:
numpy_array_from_list = np.array([1, 2, 3, 4, 5])
two_dimensional_list = np.array([[0, 1, 2],
                                 [3, 4, 5],
                                 [6, 7, 8]])

print('The size:', numpy_array_from_list.size)  # 5
print('The size:', two_dimensional_list.size)  # 3


The size: 5
The size: 9


## Mathematical Operation using numpy
***

NumPy array is not like exactly like python list. To do mathematical operation in Python list we have to looop through the items but numpy can allow to do any mathematical operation without looping. Mathematical Operation:

-Addition (+)

-Subtraction (-)

-Multiplication (\*)

-Division (/)

-Modules (%)

-Floor Division(//)

-Exponential(\*\*)


### Addition

In [113]:
# Mathematical Operation
# Addition
numpy_array_from_list = np.array([1, 2, 3, 4, 5])
print('original array: ', numpy_array_from_list)
ten_plus_original = numpy_array_from_list  + 10
print(ten_plus_original)

original array:  [1 2 3 4 5]
[11 12 13 14 15]


### Substraction

In [114]:
# Subtraction
numpy_array_from_list = np.array([1, 2, 3, 4, 5])
print('original array: ', numpy_array_from_list)
ten_minus_original = numpy_array_from_list  - 10
print(ten_minus_original)

original array:  [1 2 3 4 5]
[-9 -8 -7 -6 -5]


### Multiplication

In [115]:
# Multiplication
numpy_array_from_list = np.array([1, 2, 3, 4, 5])
print('original array: ', numpy_array_from_list)
ten_times_original = numpy_array_from_list * 10
print(ten_times_original)

original array:  [1 2 3 4 5]
[10 20 30 40 50]


### Division

In [116]:
# Division
numpy_array_from_list = np.array([1, 2, 3, 4, 5])
print('original array: ', numpy_array_from_list)
ten_times_original = numpy_array_from_list / 10
print(ten_times_original)

original array:  [1 2 3 4 5]
[0.1 0.2 0.3 0.4 0.5]


### Modulus

In [117]:
# Modulus; Finding the remainder
numpy_array_from_list = np.array([1, 2, 3, 4, 5])
print('original array: ', numpy_array_from_list)
ten_times_original = numpy_array_from_list % 3
print(ten_times_original)

original array:  [1 2 3 4 5]
[1 2 0 1 2]


### Floor Division

In [118]:
# Floor division: the division result without the remainder
numpy_array_from_list = np.array([1, 2, 3, 4, 5])
print('original array: ', numpy_array_from_list)
ten_times_original = numpy_array_from_list // 10
print(ten_times_original)

original array:  [1 2 3 4 5]
[0 0 0 0 0]


### Exponential

In [119]:
# Exponential is finding some number the power of another:
numpy_array_from_list = np.array([1, 2, 3, 4, 5])
print('original array: ', numpy_array_from_list)
ten_times_original = numpy_array_from_list  ** 2
print(ten_times_original)

original array:  [1 2 3 4 5]
[ 1  4  9 16 25]



## Checking data types
***

In [120]:
#Int,  Float numbers
numpy_int_arr = np.array([1,2,3,4])
numpy_float_arr = np.array([1.1, 2.0,3.2])
numpy_bool_arr = np.array([-3, -2, 0, 1,2,3], dtype='bool')

print(numpy_int_arr.dtype)
print(numpy_float_arr.dtype)
print(numpy_bool_arr.dtype)

int32
float64
bool


### Converting types
We can convert the datatypes of numpy array

1. Int to float

In [121]:
numpy_int_arr = np.array([1,2,3,4], dtype = 'float')
numpy_int_arr

array([1., 2., 3., 4.])

2. Float to int

In [122]:
numpy_int_arr = np.array([1., 2., 3., 4.], dtype = 'int')
numpy_int_arr

array([1, 2, 3, 4])

3. Int to boolean

In [123]:
np.array([-3, -2, 0, 1,2,3], dtype='bool')

array([ True,  True, False,  True,  True,  True])

4. Int to str

In [124]:
numpy_int_arr = np.array([1,2,3,4])
numpy_int_arr.astype('int').astype('str')

array(['1', '2', '3', '4'], dtype='<U11')

## Multi-dimensional Arrays
***

In [125]:
# 2 Dimension Array
two_dimension_array = np.array([(1,2,3),(4,5,6), (7,8,9)])
print(type (two_dimension_array))
print(two_dimension_array)
print('Shape: ', two_dimension_array.shape)
print('Size:', two_dimension_array.size)
print('Data type:', two_dimension_array.dtype)

<class 'numpy.ndarray'>
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Shape:  (3, 3)
Size: 9
Data type: int32


### Getting items from a numpy array

In [126]:
# 2 Dimension Array
two_dimension_array = np.array([[1,2,3],[4,5,6], [7,8,9]])
first_row = two_dimension_array[0]
second_row = two_dimension_array[1]
third_row = two_dimension_array[2]
print('First row:', first_row)
print('Second row:', second_row)
print('Third row: ', third_row)
print(two_dimension_array)

First row: [1 2 3]
Second row: [4 5 6]
Third row:  [7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [127]:
first_column= two_dimension_array[:,0]
second_column = two_dimension_array[:,1]
third_column = two_dimension_array[:,2]
print('First column:', first_column)
print('Second column:', second_column)
print('Third column: ', third_column)
print(two_dimension_array)

First column: [1 4 7]
Second column: [2 5 8]
Third column:  [3 6 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


## Slicing Numpy array
***

Slicing in numpy is similar to slicing in python list:

In [128]:
three_dimension_array = np.array([[1,2,3],[4,5,6], [7,8,9]])
first_two_rows_and_columns = three_dimension_array[0:2, 0:2]
print(first_two_rows_and_columns)

[[1 2]
 [4 5]]


### How to reverse the rows and the whole array?


In [135]:
two_dimension_array[::-1]

array([[7, 8, 9],
       [4, 5, 6],
       [1, 2, 3]])

### Reverse the row and column positions

In [136]:
two_dimension_array = np.array([[1,2,3],[4,5,6], [7,8,9]])
two_dimension_array[::-1,::-1]

array([[9, 8, 7],
       [6, 5, 4],
       [3, 2, 1]])

## How to represent missing values?
***

In [140]:
print(two_dimension_array)
two_dimension_array[1,1] = 55
two_dimension_array[1,2] = 44
print(two_dimension_array)

[[ 1  2  3]
 [ 4 55 44]
 [ 7  8  9]]
[[ 1  2  3]
 [ 4 55 44]
 [ 7  8  9]]


In [142]:
# Numpy Zeroes
# numpy.zeros(shape, dtype=float, order='C')
numpy_zeroes = np.zeros((3,3),dtype=int,order='C')
numpy_zeroes

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [143]:
# Numpy Zeroes
numpy_ones = np.ones((3,3),dtype=int,order='C')
print(numpy_ones)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [146]:
twoes = numpy_ones * 2
print(twoes)

[[2 2 2]
 [2 2 2]
 [2 2 2]]


In [148]:
# Reshape
# numpy.reshape(), numpy.flatten()
first_shape  = np.array([(1,2,3), (4,5,6)])
print(first_shape)
reshaped = first_shape.reshape(3,2)
print(reshaped)

[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]


In [149]:
flattened = reshaped.flatten()
print(flattened)

[1 2 3 4 5 6]


In [150]:
## Horitzontal Stack
np_list_one = np.array([1,2,3])
np_list_two = np.array([4,5,6])

print(np_list_one + np_list_two)

print('Horizontal Append:', np.hstack((np_list_one, np_list_two)))

[5 7 9]
Horizontal Append: [1 2 3 4 5 6]


In [151]:
## Vertical Stack
print('Vertical Append:', np.vstack((np_list_one, np_list_two)))

Vertical Append: [[1 2 3]
 [4 5 6]]
